name: Build WaveScanPro APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Ensure Gradle Wrapper JAR
      run: |
        if [ ! -s gradle/wrapper/gradle-wrapper.jar ]; then
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://repo.gradle.org/artifactory/libs-release-bintray/gradle/wrapper/gradle-wrapper.jar
        fi
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
      env:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g"
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WaveScanPro-APK
        path: app/build/outputs/apk/debug/app-debug.apk
